version: '3.8'
services:
  client:
    build:
      context: ubuntu
    restart: always
    environment:
      REDIS_OM_URL: "redis://default:5uper53cret@enterprise.redis.com:9139"
    volumes:
      - ./data/client:/data

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports: [ 6379, 8001 ]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/redis:/data

volumes:
  data:
    driver: local



